### ISSUE TITLE
ClUB

### ISSUE THREAD

**Issue by lixuyuan102** [baneitixiaomai/MIRV#2]
Thanks for sharing your code. However, the club estimator seems not to be trained. It seems like the 'kl_dis' function in  Mutual_info_reg  is useless.

**Comment by baneitixiaomai** [comment]
Thank you for your interest in our work. In lines 73-81 of the [code](https://github.com/baneitixiaomai/MIRV/blob/main/first_stage/model/ResNet_VGG_models.py) is the process of calculating the CLUB, which corresponds to the _Technical details_ section on page 5 of the paper.

**Comment by lixuyuan102** [comment]
> Thank you for your interest in our work. In lines 73-81 of the [code](https://github.com/baneitixiaomai/MIRV/blob/main/first_stage/model/ResNet_VGG_models.py) is the process of calculating the CLUB, which corresponds to the _Technical details_ section on page 5 of the paper.

The code 73-81 is used to compute the upper bound of MI for training the network of the main task. However, as the club [paper 3.2](https://arxiv.org/abs/2006.12013) the neural club estimator requires separate training to approximate p(y|x) which allows the estimator to give a correct upper bound of MI. I'm just confused as to whether the estimator without being individually trained can give an upper bound of MI that supports the decoupling task.

**Comment by baneitixiaomai** [comment]
Mutual_info_reg is actually a trainable module (e.g., the theta parameter of Eqs. 4 and 5 of the paper), although the inputs are features of the main network, and Table IV of the paper demonstrates the effectiveness of this module.

**Comment by lixuyuan102** [comment]
> Mutual_info_reg is actually a trainable module (e.g., the theta parameter of Eqs. 4 and 5 of the paper), although the inputs are features of the main network, and Table IV of the paper demonstrates the effectiveness of this module.

Get it! Thanks for your reply.
